In [1]:
from mxnet import ndarray as nd

In [2]:
# 3行 2列的矩阵，并初始化为 0
nd.zeros((3, 4))


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

In [3]:
# 初始化为 1
nd.ones((3, 4))


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [4]:
nd.array([[1, 2], [3, 4]])


[[ 1.  2.]
 [ 3.  4.]]
<NDArray 2x2 @cpu(0)>

In [5]:
# 随机数
# 均值为0， 方差为1 正态分布
a = nd.random_normal(0, 1, shape=(3,4))
print(a)
print(a.size)
a.shape


[[ 0.23107234  0.30030754 -0.32433936  1.04932904]
 [ 0.7368623  -0.0097888   0.46656415  1.72023427]
 [ 0.87809837 -1.07333779 -0.86925656 -0.26717702]]
<NDArray 3x4 @cpu(0)>
12


(3, 4)

In [6]:
# exp -> 指数运算
# dot -> 矩阵乘法
# T   -> 转置

# Numpy 转换

In [7]:
import numpy as np
x = np.ones((2, 3))
# numpy -> mxnet
y = nd.array(x)
# mxnet -> numpy
z = y.asnumpy()
print([z, y])
print(type(z))
print(type(y))

[array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32), 
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>]
<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>
